[package]
name = "lynx-proc"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
description = "procfs collectors for LynxOps"

[dependencies]
lynx-core.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
libc.workspace = true
